### ISSUE TITLE
some models have weird displaced mesh objects

### ISSUE THREAD

**Issue by steventylerseanherr** [Joschuka/fmt_mmdl#1]
as the title says some mmdls dont seem to import correctly and some of the mesh objects end up in weird places like this
![image](https://user-images.githubusercontent.com/48705919/138031708-bdab7b22-e3ca-49d7-87b0-cde5b16e4b3c.png)
(samus.pkg / 7493446503205414601.mmdl)
or this
![image](https://user-images.githubusercontent.com/48705919/138031874-e278aea5-b294-436c-ae98-44a50a5158e3.png)
(s090_skybase.pkg / 732919528301476980.mmdl)

**Comment by Joschuka** [comment]
Yeah I noticed. I'll take a look after adding animation support.

**Comment by Reploidsham** [comment]
The skeleton seems to export weird is what it is, the head bone is still connected so something goes weird on bone orientation.

Edit: I'm adding in a thanks for your hard work .I expected you to stop when you said you were going to before because you immediately did a good amount in regards to unpacking for this.

**Comment by steventylerseanherr** [comment]
i dont think it is related to the skeleton as the head bone is where it should be (right at the top of the neck bone)

its just the verts inside the mesh object are offset by something
i talked to m-1 about it on discord and they assume its something related to bone indices

and yeah i really owe you joschuka and m-1 for working on the model formats
i love you guys and thanks so much for whats already done

**Comment by Joschuka** [comment]
> 
> 
> The skeleton seems to export weird is what it is, the head bone is still connected so something goes weird on bone orientation.

Are you referring to the weird bones orientation in Blender ? If you use fbx this is  unfortunately due to Blender's default fbx importer and its conventions used to represent bones. You get the same problem if you import some fbx exported from Unreal Engine. The bones do deform correctly but they'll look messy, what I usually suggest is to change the bone shape to something custom like spheres or use the betterfbx plugin to load these correctly, here's a comparison :


![default](https://user-images.githubusercontent.com/43338144/138399254-40eeb68c-ddf6-4651-ac9d-858a959e15ef.PNG)

![betterfbx](https://user-images.githubusercontent.com/43338144/138399285-2cf09cd2-c73a-42d1-864d-4e274b419720.PNG)

I still don't know why they adopted this representation, it just confuses people on the whole concept of joint for deformation and leads to dumb things like this, with all these tails hanging around for the end bones.
But well it works at least and the animations too, it's just not very pleasing to look at if you don't change the shape.

> Edit: I'm adding in a thanks for your hard work .I expected you to stop when you said you were going to before because you immediately did a good amount in regards to unpacking for this.

You're welcome, I was planning to but the hash function was figured out and since it was the only thing I was missing for animation support I decided to work more on the format. 

> 
> 
> i dont think it is related to the skeleton as the head bone is where it should be (right at the top of the neck bone)
> 
> its just the verts inside the mesh object are offset by something i talked to m-1 about it on discord and they assume its something related to bone indices

Indeed, it's a pure geometry problem, basically some meshes with a special skinning type have to be transformed but apparently it fails on a few of these, I'll have to investigate why now that anim support is implemented, maybe this week-end if I have the time or next week, M-1 is taking a look at it too so he may solve it before me.

> and yeah i really owe you joschuka and m-1 for working on the model formats i love you guys and thanks so much for whats already done

You're welcome, glad you enjoy the plugin.

**Comment by Joschuka** [comment]
Alright I finally took a look and pushed a new version, let me know how it goes.

**Comment by Bearborg** [comment]
This version fixed a lot of models, but some others still appear to have issues. `actors\characters\gobbler\models\gobbler_test.bcmdl` and `actors\characters\chozowarrior\models\chozowarrior.bcmdl` are two examples where the displaced meshes have moved from their previous locations, but still don't appear to be in the right locations.
![image](https://user-images.githubusercontent.com/3048890/139519371-62d6fc4d-fda5-4bec-a79b-42da57d81de2.png)
![image](https://user-images.githubusercontent.com/3048890/139519472-4f0fb1b7-40ec-4b77-b7af-9acd5b140e41.png)

**Comment by steventylerseanherr** [comment]
yep
hyper suit samus is fixed
the chozo commander models is fixed
samuss cutscene face models are fixed as well
but like bearborg said the chozo warriors have problems (and probably more)

**Comment by Joschuka** [comment]
Ok M-1 found the issue and I pushed some fixes, let me know if some models are still broken.
